export const CREATE_USER = 'USER/CREATE_USER'
export const DELETE_USER = 'USER/DELETE_USER'
export const EDIT_USER = 'USER/EDIT_USER'
export const GET_USERS = 'USER/GET_USERS'
export const GET_USER = 'USER/GET_USER'
export const USER_ERROR = 'USER_ERROR'
