export const INCREMENT = 'COUNTER/INCREMENT';
export const DECREMENT = 'COUNTER/DECREMENT';

export const CREATE_USER = 'USERS/CREATE_USER'
export const DELETE_USER = 'USERS/DELETE_USER'
export const EDIT_USER = 'USERS/EDIT_USER'
export const GET_USERS = 'USERS/GET_USERS'
export const GET_USER = 'USERS/GET_USER'

export const CREATE_POST = 'POSTS/CREATE_POST'
export const DELETE_POST = 'POSTS/DELETE_POST'
export const EDIT_POST = 'POSTS/EDIT_POST'
export const GET_POSTS = 'POSTS/GET_POSTS'
export const GET_POST = 'POSTS/GET_POST'

export const LOADING = 'USERS/LOADING'

export const ERROR = 'USERS/ERROR'